name: "clientdeploy"

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  

jobs:
  zip:
    name: "deploy client"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git switch "dist"
          git archive -o modpack.zip modpack
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'          
          git add modpack.zip
          git commit -am "Automated report"
