name: "clientdeploy"

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  

jobs:
  pre-release:
    name: "deploy client"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: 'modpack'
          filename: 'modpack.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
